In [1]:
# Walmart Sales Data Analysis using Python (Pandas)

In [2]:
# Importing Pandas

import pandas as pd

In [3]:
# Loading dataset

df=pd.read_csv('Walmart_Sales.csv')

In [4]:
pd.options.display.float_format = '{:,.2f}'.format

In [5]:
# Preview data

df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,"1,643,690.90",0,42.31,2.57,211.10,8.11
1,1,12-02-2010,"1,641,957.44",1,38.51,2.55,211.24,8.11
2,1,19-02-2010,"1,611,968.17",0,39.93,2.51,211.29,8.11
3,1,26-02-2010,"1,409,727.59",0,46.63,2.56,211.32,8.11
4,1,05-03-2010,"1,554,806.68",0,46.50,2.62,211.35,8.11

In [6]:
# Checking dataset structure

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6435 entries, 0 to 6434
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         6435 non-null   int64
 1   Date          6435 non-null   object
 2   Weekly_Sales  6435 non-null   float64
 3   Holiday_Flag  6435 non-null   int64
 4   Temperature   6409 non-null   float64
 5   Fuel_Price    6411 non-null   float64
 6   CPI           6435 non-null   float64
 7   Unemployment  6435 non-null   float64
dtypes: float64(5), int64(2), object(1)
memory usage: 402.3+ KB

In [7]:
# Statistical summary

df.describe()

,Store,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
count,"6,435.00","6,435.00","6,435.00","6,409.00","6,411.00","6,435.00","6,435.00"
mean,23.00,"1,046,964.88",0.07,60.64,3.36,171.58,8.00
std,12.99,"564,366.62",0.26,18.44,0.46,39.36,1.88
min,1.00,"209,986.25",0.00,-2.06,2.47,126.06,3.88
25%,12.00,"553,350.10",0.00,47.41,2.93,131.74,6.89
50%,23.00,"960,746.04",0.00,62.63,3.45,182.62,7.87
75%,34.00,"1,420,158.66",0.00,74.90,3.73,212.74,8.62
max,45.00,"3,818,686.45",1.00,100.14,4.47,227.23,14.31

In [8]:
# Converting date column to datetime

df['Date']=pd.to_datetime(df['Date'],dayfirst=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6435 entries, 0 to 6434
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         6435 non-null   int64
 1   Date          6435 non-null   datetime64[ns]
 2   Weekly_Sales  6435 non-null   float64
 3   Holiday_Flag  6435 non-null   int64
 4   Temperature   6409 non-null   float64
 5   Fuel_Price    6411 non-null   float64
 6   CPI           6435 non-null   float64
 7   Unemployment  6435 non-null   float64
dtypes: datetime64[ns](1), float64(5), int64(2)
memory usage: 402.3 KB

In [10]:
# Filling missing temperature

df['Temperature']=df['Temperature'].fillna(df['Temperature'].median())

In [11]:
# Filling missing fuel price

df['Fuel_Price']=df['Fuel_Price'].fillna(df['Fuel_Price'].median())

In [12]:
# Extracting month from date

df['Month']=df['Date'].dt.month

In [13]:
# # Extracting year from date

df['Year']=df['Date'].dt.year

In [14]:
df

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Month,Year
0,1,2010-02-05,"1,643,690.90",0,42.31,2.57,211.10,8.11,2,2010
1,1,2010-02-12,"1,641,957.44",1,38.51,2.55,211.24,8.11,2,2010
2,1,2010-02-19,"1,611,968.17",0,39.93,2.51,211.29,8.11,2,2010
3,1,2010-02-26,"1,409,727.59",0,46.63,2.56,211.32,8.11,2,2010
4,1,2010-03-05,"1,554,806.68",0,46.50,2.62,211.35,8.11,3,2010
...,...,...,...,...,...,...,...,...,...,...
6430,45,2012-09-28,"713,173.95",0,64.88,4.00,192.01,8.68,9,2012
6431,45,2012-10-05,"733,455.07",0,64.89,3.98,192.17,8.67,10,2012
6432,45,2012-10-12,"734,464.36",0,54.47,4.00,192.33,8.67,10,2012
6433,45,2012-10-19,"718,125.53",0,56.47,3.97,192.33,8.67,10,2012
6434,45,2012-10-26,"760,281.43",0,58.85,3.88,192.31,8.67,10,2012

In [15]:
# Total sales by store

store_sales_2012=df[df['Year']==2012].groupby('Store')['Weekly_Sales'].sum().sort_values(ascending=False)

In [16]:
store_sales_2012

Store
4    92,771,189.24
20   89,827,709.38
13   86,707,455.02
2    81,496,695.37
10   78,228,616.94
14   77,441,398.26
27   71,920,056.12
1    68,202,058.02
6    66,315,047.00
39   65,885,662.85
31   59,884,407.22
19   59,212,433.28
23   58,767,978.75
11   58,184,065.68
24   57,186,396.17
41   56,887,839.93
28   55,328,907.07
32   50,281,116.00
18   44,918,576.80
12   43,334,845.72
26   42,976,444.29
22   42,655,656.23
34   41,739,164.15
40   41,172,407.34
17   40,285,378.63
8    39,233,920.13
35   35,237,722.52
45   32,723,630.17
21   30,251,886.71
25   29,490,505.71
43   26,975,233.97
7    25,367,556.47
42   24,950,359.85
15   24,827,530.71
9    23,974,029.58
37   22,612,774.69
29   22,244,381.62
16   22,102,425.32
30   18,795,650.08
38   18,631,073.45
3    18,024,439.50
44   14,187,373.72
5    14,168,838.13
36   13,286,470.53
33   11,435,551.03
Name: Weekly_Sales, dtype: float64

In [17]:
df

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Month,Year
0,1,2010-02-05,"1,643,690.90",0,42.31,2.57,211.10,8.11,2,2010
1,1,2010-02-12,"1,641,957.44",1,38.51,2.55,211.24,8.11,2,2010
2,1,2010-02-19,"1,611,968.17",0,39.93,2.51,211.29,8.11,2,2010
3,1,2010-02-26,"1,409,727.59",0,46.63,2.56,211.32,8.11,2,2010
4,1,2010-03-05,"1,554,806.68",0,46.50,2.62,211.35,8.11,3,2010
...,...,...,...,...,...,...,...,...,...,...
6430,45,2012-09-28,"713,173.95",0,64.88,4.00,192.01,8.68,9,2012
6431,45,2012-10-05,"733,455.07",0,64.89,3.98,192.17,8.67,10,2012
6432,45,2012-10-12,"734,464.36",0,54.47,4.00,192.33,8.67,10,2012
6433,45,2012-10-19,"718,125.53",0,56.47,3.97,192.33,8.67,10,2012
6434,45,2012-10-26,"760,281.43",0,58.85,3.88,192.31,8.67,10,2012

In [18]:
# Filtering data for Store 33

df[df['Store']==33]

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Month,Year
4576,33,2010-02-05,"274,593.43",0,58.40,2.96,126.44,10.12,2,2010
4577,33,2010-02-12,"294,882.83",1,55.47,2.83,126.50,10.12,2,2010
4578,33,2010-02-19,"296,850.83",0,62.16,2.92,126.53,10.12,2,2010
4579,33,2010-02-26,"284,052.77",0,56.50,2.83,126.55,10.12,2,2010
4580,33,2010-03-05,"291,484.89",0,59.17,2.88,126.58,10.12,3,2010
...,...,...,...,...,...,...,...,...,...,...
4714,33,2012-09-28,"242,813.51",0,86.42,3.97,131.04,7.15,9,2012
4715,33,2012-10-05,"265,444.90",0,85.18,4.13,131.08,6.89,10,2012
4716,33,2012-10-12,"291,781.15",0,79.64,4.47,131.11,6.89,10,2012
4717,33,2012-10-19,"254,412.34",0,75.55,4.45,131.15,6.89,10,2012
4718,33,2012-10-26,"253,731.13",0,73.70,4.30,131.19,6.89,10,2012

In [19]:
# Monthly sales trend

Monthly_sales=df.groupby(['Year','Month'])['Weekly_Sales'].sum()

In [20]:
Monthly_sales

Year  Month
2010  2       190,332,983.04
      3       181,919,802.50
      4       231,412,368.05
      5       186,710,934.34
      6       192,246,172.36
      7       232,580,125.98
      8       187,640,110.89
      9       177,267,896.37
      10      217,161,824.02
      11      202,853,370.14
      12      288,760,532.72
2011  1       163,703,966.83
      2       186,331,327.87
      3       179,356,448.29
      4       226,526,510.97
      5       181,648,158.16
      6       189,773,385.19
      7       229,911,398.87
      8       188,599,332.25
      9       220,847,738.42
      10      183,261,283.15
      11      210,162,354.87
      12      288,078,102.48
2012  1       168,894,471.66
      2       192,063,579.54
      3       231,509,650.49
      4       188,920,905.95
      5       188,766,479.45
      6       240,610,329.29
      7       187,509,452.40
      8       236,850,765.68
      9       180,645,544.47
      10      184,361,680.42
Name: Weekly_Sales, dtype: float64

In [21]:
# Yearly sales

yearly_sales=df.groupby('Year')['Weekly_Sales'].sum()

In [22]:
yearly_sales

Year
2010   2,288,886,120.41
2011   2,448,200,007.35
2012   2,000,132,859.35
Name: Weekly_Sales, dtype: float64

In [23]:
# Holiday vs Non-Holiday sales

holiday_sales=df.groupby('Holiday_Flag')['Weekly_Sales'].mean()


# Average weekly sales during holidays are higher than non-holiday periods (1.04M), indicating that sales tend to increase during holiday periods.

In [24]:
holiday_sales

Holiday_Flag
0   1,041,256.38
1   1,122,887.89
Name: Weekly_Sales, dtype: float64

In [25]:
# Pivot table

monthly_sales_table=df.pivot_table(values='Weekly_Sales',index='Month',columns='Year',aggfunc='sum')

In [26]:
monthly_sales_table

Year            2010           2011           2012
Month
1                NaN 163,703,966.83 168,894,471.66
2     190,332,983.04 186,331,327.87 192,063,579.54
3     181,919,802.50 179,356,448.29 231,509,650.49
4     231,412,368.05 226,526,510.97 188,920,905.95
5     186,710,934.34 181,648,158.16 188,766,479.45
6     192,246,172.36 189,773,385.19 240,610,329.29
7     232,580,125.98 229,911,398.87 187,509,452.40
8     187,640,110.89 188,599,332.25 236,850,765.68
9     177,267,896.37 220,847,738.42 180,645,544.47
10    217,161,824.02 183,261,283.15 184,361,680.42
11    202,853,370.14 210,162,354.87            NaN
12    288,760,532.72 288,078,102.48            NaN

In [27]:
# Calculating sales difference between 2012 and 2011

monthly_sales_table['2012_vs_2011']=monthly_sales_table[2012]-monthly_sales_table[2011]

In [28]:
monthly_sales_table

Year            2010           2011           2012   2012_vs_2011
Month
1                NaN 163,703,966.83 168,894,471.66   5,190,504.83
2     190,332,983.04 186,331,327.87 192,063,579.54   5,732,251.67
3     181,919,802.50 179,356,448.29 231,509,650.49  52,153,202.20
4     231,412,368.05 226,526,510.97 188,920,905.95 -37,605,605.02
5     186,710,934.34 181,648,158.16 188,766,479.45   7,118,321.29
6     192,246,172.36 189,773,385.19 240,610,329.29  50,836,944.10
7     232,580,125.98 229,911,398.87 187,509,452.40 -42,401,946.47
8     187,640,110.89 188,599,332.25 236,850,765.68  48,251,433.43
9     177,267,896.37 220,847,738.42 180,645,544.47 -40,202,193.95
10    217,161,824.02 183,261,283.15 184,361,680.42   1,100,397.27
11    202,853,370.14 210,162,354.87            NaN            NaN
12    288,760,532.72 288,078,102.48            NaN            NaN

In [29]:
# Calculating year-over-year percentage change (2012 vs 2011)


monthly_sales_table['YoY_percent']=(((monthly_sales_table[2012]-monthly_sales_table[2011])/monthly_sales_table[2011])*100)


# Year-over-year analysis shows that March, June, and August experienced the highest growth, indicating these months contributed significantly to overall sales growth.

In [30]:
monthly_sales_table.sort_values(by='YoY_percent',ascending=False)

Year            2010           2011           2012   2012_vs_2011  YoY_percent
Month
3     181,919,802.50 179,356,448.29 231,509,650.49  52,153,202.20        29.08
6     192,246,172.36 189,773,385.19 240,610,329.29  50,836,944.10        26.79
8     187,640,110.89 188,599,332.25 236,850,765.68  48,251,433.43        25.58
5     186,710,934.34 181,648,158.16 188,766,479.45   7,118,321.29         3.92
1                NaN 163,703,966.83 168,894,471.66   5,190,504.83         3.17
2     190,332,983.04 186,331,327.87 192,063,579.54   5,732,251.67         3.08
10    217,161,824.02 183,261,283.15 184,361,680.42   1,100,397.27         0.60
4     231,412,368.05 226,526,510.97 188,920,905.95 -37,605,605.02       -16.60
9     177,267,896.37 220,847,738.42 180,645,544.47 -40,202,193.95       -18.20
7     232,580,125.98 229,911,398.87 187,509,452.40 -42,401,946.47       -18.44
11    202,853,370.14 210,162,354.87            NaN            NaN          NaN
12    288,760,532.72 288,078,102.48            NaN            NaN          NaN

In [31]:
# Sorting months by sales difference between 2012 and 2011


monthly_sales_table.sort_values(by='2012_vs_2011',ascending=False)


# Month-wise comparison between 2012 and 2011 shows that March, June, and August recorded the highest growth, with sales increasing by over 48M, making them the top contributors to year-over-year sales improvement.

Year            2010           2011           2012   2012_vs_2011  YoY_percent
Month
3     181,919,802.50 179,356,448.29 231,509,650.49  52,153,202.20        29.08
6     192,246,172.36 189,773,385.19 240,610,329.29  50,836,944.10        26.79
8     187,640,110.89 188,599,332.25 236,850,765.68  48,251,433.43        25.58
5     186,710,934.34 181,648,158.16 188,766,479.45   7,118,321.29         3.92
2     190,332,983.04 186,331,327.87 192,063,579.54   5,732,251.67         3.08
1                NaN 163,703,966.83 168,894,471.66   5,190,504.83         3.17
10    217,161,824.02 183,261,283.15 184,361,680.42   1,100,397.27         0.60
4     231,412,368.05 226,526,510.97 188,920,905.95 -37,605,605.02       -16.60
9     177,267,896.37 220,847,738.42 180,645,544.47 -40,202,193.95       -18.20
7     232,580,125.98 229,911,398.87 187,509,452.40 -42,401,946.47       -18.44
11    202,853,370.14 210,162,354.87            NaN            NaN          NaN
12    288,760,532.72 288,078,102.48            NaN            NaN          NaN

In [32]:
df

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Month,Year
0,1,2010-02-05,"1,643,690.90",0,42.31,2.57,211.10,8.11,2,2010
1,1,2010-02-12,"1,641,957.44",1,38.51,2.55,211.24,8.11,2,2010
2,1,2010-02-19,"1,611,968.17",0,39.93,2.51,211.29,8.11,2,2010
3,1,2010-02-26,"1,409,727.59",0,46.63,2.56,211.32,8.11,2,2010
4,1,2010-03-05,"1,554,806.68",0,46.50,2.62,211.35,8.11,3,2010
...,...,...,...,...,...,...,...,...,...,...
6430,45,2012-09-28,"713,173.95",0,64.88,4.00,192.01,8.68,9,2012
6431,45,2012-10-05,"733,455.07",0,64.89,3.98,192.17,8.67,10,2012
6432,45,2012-10-12,"734,464.36",0,54.47,4.00,192.33,8.67,10,2012
6433,45,2012-10-19,"718,125.53",0,56.47,3.97,192.33,8.67,10,2012
6434,45,2012-10-26,"760,281.43",0,58.85,3.88,192.31,8.67,10,2012

In [33]:
# Sorting monthly sales by 2012 in descending order


monthly_sales_table.sort_values(by=2012,ascending=False)


# Monthly sales analysis shows that June, August, and March 2012 recorded the highest sales, each exceeding 230M, with strong year-over-year growth of 25–29%.

Year            2010           2011           2012   2012_vs_2011  YoY_percent
Month
6     192,246,172.36 189,773,385.19 240,610,329.29  50,836,944.10        26.79
8     187,640,110.89 188,599,332.25 236,850,765.68  48,251,433.43        25.58
3     181,919,802.50 179,356,448.29 231,509,650.49  52,153,202.20        29.08
2     190,332,983.04 186,331,327.87 192,063,579.54   5,732,251.67         3.08
4     231,412,368.05 226,526,510.97 188,920,905.95 -37,605,605.02       -16.60
5     186,710,934.34 181,648,158.16 188,766,479.45   7,118,321.29         3.92
7     232,580,125.98 229,911,398.87 187,509,452.40 -42,401,946.47       -18.44
10    217,161,824.02 183,261,283.15 184,361,680.42   1,100,397.27         0.60
9     177,267,896.37 220,847,738.42 180,645,544.47 -40,202,193.95       -18.20
1                NaN 163,703,966.83 168,894,471.66   5,190,504.83         3.17
11    202,853,370.14 210,162,354.87            NaN            NaN          NaN
12    288,760,532.72 288,078,102.48            NaN            NaN          NaN

In [34]:
# Correlation between CPI and Sales


df[['CPI','Weekly_Sales']].corr()


# As CPI increases, sales slightly decrease, but the effect is almost negligible.

               CPI  Weekly_Sales
CPI           1.00         -0.07
Weekly_Sales -0.07          1.00

In [35]:
# Correation between unemployment and sales


df[['Unemployment','Weekly_Sales']].corr()


# There is a weak negative correlation (-0.11) between unemployment rate and weekly sales, suggesting that higher unemployment may slightly reduce sales, but the relationship is not strong enough to be a key driving factor.

              Unemployment  Weekly_Sales
Unemployment          1.00         -0.11
Weekly_Sales         -0.11          1.00

In [36]:
# Correlation between fuel price and sales


df[['Fuel_Price','Weekly_Sales']].corr()


# There is almost no correlation between fuel prices and weekly sales,indicating fuel price fluctuations do no significantly influence sales trends.

              Fuel_Price  Weekly_Sales
Fuel_Price          1.00          0.01
Weekly_Sales        0.01          1.00